config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users do
    resource :shop

    member do
      get :name
    end

    collection do
      get :count
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'users#index'
end

app/models/shop.rb
# frozen_string_literal: true

class Shop
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String

  validates :name, presence: true

  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User
  include Mongoid::Document
  include Mongoid::Timestamps

  field :age,        type: Integer
  field :first_name, type: String
  field :gender,     type: String
  field :last_name,  type: String
  field :address,    type: Hash

  GENDERS = %w[male female others].freeze

  validates :first_name, :last_name, presence: true
  validates :age, numericality: { only_integer: true,
                                  greater_than_or_equal_to: 0 }
  validates :gender, inclusion: { in: GENDERS }, allow_blank: true

  has_one :shop

  def full_address
    address['address_2'] + ', ' + address['address_1'] + ', ' + address['country']
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/shops_controller.rb
# frozen_string_literal: true

class ShopsController < ApplicationController
  before_action :set_user
  before_action :set_shop, only: %i[show new create edit update destroy]

  def new; end

  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @user, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to user_shop_path(@user), notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  def show; end

  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to user_url(@user), notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_shop
    @shop = @user.shop || Shop.new
  end

  def shop_params
    params.require(:shop)
          .permit(:name)
          .merge(user: @user)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :prepare_genders, only: %i[new create edit update]
  before_action :set_user, only: %i[show edit update destroy name]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    # For fields_for to autofill value
    @address = OpenStruct.new(@user.address)
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /users/count
  # GET /users/count.json
  def count
    @count = User.count
  end

  # GET /users/:id/name
  # GET /users/:id/name.json
  def name; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :age,
                                 :gender,
                                 address: %i[country address_1 address_2])
  end

  def prepare_genders
    @genders = User::GENDERS.map { |v| [v.capitalize, v] }
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/shops_helper.rb
# frozen_string_literal: true

module ShopsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Onboarding</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shops/_form.html.erb
<%= form_with(model: shop, local: true, url: user_shop_path) do |form| %>
  <% if shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Editing Shop</h1>

<%= render 'form', shop: @shop, user: @user %>

<%= link_to 'Back', user_path(@user) %>

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form', shop: @shop, user: @user %>

<%= link_to 'Back', user_path(@user) %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= "#{@user.first_name} #{@user.last_name}" %>
</p>

<p>
  <strong>Shop Name:</strong>
  <%= @user.shop.name %>
</p>

<%= link_to 'Edit', edit_user_shop_path(@user) %> |
<%= link_to 'Destroy', user_shop_path(@user), method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', user_path(@user) %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, min: 0 %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.select :gender, @genders, include_blank: true %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.fields_for :address, @address do |f| %>
        <%= f.text_field :country, placeholder: 'Country' %>
        <%= f.text_field :address_1, placeholder: 'Address 1' %>
        <%= f.text_field :address_2, placeholder: 'Address 2' %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/count.html.erb
<h1>Total users:</h1>
<p>
    <%= @count %>
</p>

<%= link_to 'Back', users_path %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>#</th>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to  user.id, name_user_path(user) %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/name.html.erb
<h1>Name</h1>
<h2><%= "#{@user.first_name} #{@user.last_name}" %></h2>
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender.capitalize %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.full_address %>
</p>

<p>
  <strong>Shop:</strong>
    <% if @user.shop.present? %>
      <%= link_to 'more', user_shop_path(@user) %>
    <% else %>
      <%= link_to  'Create Shop', new_user_shop_path(@user) %>
    <% end %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>